### ISSUE TITLE
How to traverse the resulting XML

### ISSUE THREAD

**Issue by abulka** [mbdevpl/open-fortran-parser-xml#12]
I've managed to generate an XML - can I please have some advice or code snippets on how to traverse it in Python? I'm familiar with traversing Python AST trees using the visitor pattern (built into Python), and am familiar with the Listener walking approach of Antlr (which I prefer). 

P.S. Would anyone have a open-fortran antlr4 grammar as the open-fortran project only has an antlr3 grammar, and antlr3 has pretty bad Python generation capability.

**Comment by mbdevpl** [comment]
Well, XML traversal is up to XML library you'd use to traverse it. If your question boils down to "How to traverse XML in Python?" then this is an example (built-in) library: https://docs.python.org/3/library/xml.etree.elementtree.html

The open-fortran-parser-xml is simply a tool to generate XML from events generated by Open Fortran Parser (implemented in Java because OFP is in Java), and Python wrapper around it. There is no special AST traversal tool provided here, there is however AST specification: https://github.com/mbdevpl/open-fortran-parser-xml#ast-specification which should help in writing whatever query/traversal/refactoring routines operating on the XML AST you'd like to write.

But if in fact what you wanna do is convert the parsed XML into Python (hinted in the P.S.) then by all means please check out my other project which uses open-fortran-parser-xml to do just that: https://github.com/mbdevpl/transpyle. You should be able to find the gory details in the `transpyle.fortran.ast_generalizer` module: https://github.com/mbdevpl/transpyle/blob/master/transpyle/fortran/ast_generalizer.py

I'm closing this issue for now, but feel free to reopen if I misunderstood something!
